apiVersion: v1
kind: Namespace
metadata:
  name: ns-jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: ns-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # For local/dev clusters, default storage class is fine. Optionally set:
  # storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: ns-jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: jenkins
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
      app.kubernetes.io/component: controller
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins
        app.kubernetes.io/component: controller
        app.kubernetes.io/part-of: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: web
        image: jenkins/jenkins:lts-jdk17
        ports:
          - name: http
            containerPort: 8080
          - name: agent
            containerPort: 50000
        env:
          - name: JENKINS_OPTS
            value: "--httpPort=8080"
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1500m"
            memory: "2Gi"
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ns-jenkins
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: controller
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: controller
  ports:
  - name: http
    port: 8082
    targetPort: 8080
    protocol: TCP
    nodePort: 30124
  - name: agent
    port: 50000
    targetPort: 50000
    protocol: TCP
